// TestAS Mathematical Equations - Practice Questions
// Variables A, B, C, D are positive integers from 1-20

export const mathChapters = [
  { id: 1, name: 'Easy', description: '2 equations, 2 variables', icon: '🟢' },
  { id: 2, name: 'Medium', description: '3 equations, 3 variables', icon: '🟡' },
  { id: 3, name: 'Hard', description: '4 equations or quadratic', icon: '🔴' },
];

export const mathLevels = [
  // ═══════════════════════════════════════════════════════════════════════════
  // EXAM 1 - Questions 1.1 to 1.20
  // ═══════════════════════════════════════════════════════════════════════════

  // Easy (Type 1) - 2 equations, 2 variables
  {
    id: 101,
    exam: 1,
    number: '1.1',
    difficulty: 'easy',
    chapterId: 1,
    equations: ['A - B = 6', 'B = A ÷ 3'],
    variables: ['A', 'B'],
    answer: { A: 9, B: 3 },
    xp: 10,
    hint: 'From equation 2: B = A/3. Substitute into equation 1: A - A/3 = 6',
  },
  {
    id: 102,
    exam: 1,
    number: '1.2',
    difficulty: 'easy',
    chapterId: 1,
    equations: ['A + B = 27', 'A = 2 × B'],
    variables: ['A', 'B'],
    answer: { A: 18, B: 9 },
    xp: 10,
    hint: 'Substitute A = 2B into the first equation: 2B + B = 27',
  },
  {
    id: 103,
    exam: 1,
    number: '1.3',
    difficulty: 'easy',
    chapterId: 1,
    equations: ['A × B = 30', 'B - A = 13'],
    variables: ['A', 'B'],
    answer: { A: 2, B: 15 },
    xp: 10,
    hint: 'From equation 2: B = A + 13. Substitute into equation 1: A × (A + 13) = 30',
  },
  {
    id: 104,
    exam: 1,
    number: '1.4',
    difficulty: 'easy',
    chapterId: 1,
    equations: ['B × 3 = A', 'A = B + 8'],
    variables: ['A', 'B'],
    answer: { A: 12, B: 4 },
    xp: 10,
    hint: 'Both equations define A. Set them equal: 3B = B + 8',
  },
  {
    id: 105,
    exam: 1,
    number: '1.5',
    difficulty: 'easy',
    chapterId: 1,
    equations: ['A = B + 5', '3 = 2 × B - A'],
    variables: ['A', 'B'],
    answer: { A: 13, B: 8 },
    xp: 10,
    hint: 'Substitute A = B + 5 into equation 2: 3 = 2B - (B + 5)',
  },
  {
    id: 106,
    exam: 1,
    number: '1.6',
    difficulty: 'easy',
    chapterId: 1,
    equations: ['B = A ÷ 2', 'A = 3 - B'],
    variables: ['A', 'B'],
    answer: { A: 2, B: 1 },
    xp: 10,
    hint: 'From equation 1: A = 2B. Substitute into equation 2: 2B = 3 - B',
  },

  // Medium (Type 2) - 3 equations, 3 variables
  {
    id: 107,
    exam: 1,
    number: '1.7',
    difficulty: 'medium',
    chapterId: 2,
    equations: ['B = C - 2', 'A ÷ 2 + B - 5 = C', 'C = B × 3'],
    variables: ['A', 'B', 'C'],
    answer: { A: 14, B: 1, C: 3 },
    xp: 15,
    hint: 'From equations 1 and 3: B = C - 2 and C = 3B. So B = 3B - 2, which gives 2B = 2, B = 1',
  },
  {
    id: 108,
    exam: 1,
    number: '1.8',
    difficulty: 'medium',
    chapterId: 2,
    equations: ['A = C² ÷ 2', 'A - B = 5', 'A - 4 = C'],
    variables: ['A', 'B', 'C'],
    answer: { A: 8, B: 3, C: 4 },
    xp: 15,
    hint: 'From equation 3: C = A - 4. Substitute into equation 1: A = (A-4)²/2',
  },
  {
    id: 109,
    exam: 1,
    number: '1.9',
    difficulty: 'medium',
    chapterId: 2,
    equations: ['B - C = 5', 'C = 9 - B', 'A × 2 = C'],
    variables: ['A', 'B', 'C'],
    answer: { A: 1, B: 7, C: 2 },
    xp: 15,
    hint: 'From equations 1 and 2: B - C = 5 and C = 9 - B. Substitute: B - (9-B) = 5',
  },
  {
    id: 110,
    exam: 1,
    number: '1.10',
    difficulty: 'medium',
    chapterId: 2,
    equations: ['A = C + 2 - B × 3', '8 - B = A', '2 = B - A'],
    variables: ['A', 'B', 'C'],
    answer: { A: 3, B: 5, C: 16 },
    xp: 15,
    hint: 'From equations 2 and 3: A = 8 - B and 2 = B - A. Substitute: 2 = B - (8-B)',
  },
  {
    id: 111,
    exam: 1,
    number: '1.11',
    difficulty: 'medium',
    chapterId: 2,
    equations: ['2A - 3 = C', 'B ÷ 2 = A', 'A + 2 = B'],
    variables: ['A', 'B', 'C'],
    answer: { A: 2, B: 4, C: 1 },
    xp: 15,
    hint: 'From equations 2 and 3: B/2 = A and A + 2 = B. Substitute: B/2 + 2 = B',
  },
  {
    id: 112,
    exam: 1,
    number: '1.12',
    difficulty: 'medium',
    chapterId: 2,
    equations: ['B - 2 + A = C + 3', 'A - C = 3', 'A ÷ 2 = C'],
    variables: ['A', 'B', 'C'],
    answer: { A: 6, B: 2, C: 3 },
    xp: 15,
    hint: 'From equations 2 and 3: A - C = 3 and A/2 = C. Substitute: A - A/2 = 3',
  },
  {
    id: 113,
    exam: 1,
    number: '1.13',
    difficulty: 'medium',
    chapterId: 2,
    equations: ['2A = B + 8', 'A ÷ C = 6', 'C = A - 10'],
    variables: ['A', 'B', 'C'],
    answer: { A: 12, B: 16, C: 2 },
    xp: 15,
    hint: 'From equations 2 and 3: A/C = 6 and C = A - 10. So A = 6(A - 10)',
  },

  // Hard (Type 3) - 4 equations, 4 variables
  {
    id: 114,
    exam: 1,
    number: '1.14',
    difficulty: 'hard',
    chapterId: 3,
    equations: ['A ÷ 2 = B', 'C - B = 8', '6 + D = B', 'A - C + D + 1 = B - 5'],
    variables: ['A', 'B', 'C', 'D'],
    answer: { A: 16, B: 8, C: 16, D: 2 },
    xp: 25,
    hint: 'Start with equations 1 and 3: A/2 = B and 6 + D = B. These help find relationships.',
  },
  {
    id: 115,
    exam: 1,
    number: '1.15',
    difficulty: 'hard',
    chapterId: 3,
    equations: ['7 - D = B', '17 = 2 × B + C - D', '12 ÷ B + 6 = A', '3 × B = C'],
    variables: ['A', 'B', 'C', 'D'],
    answer: { A: 9, B: 4, C: 12, D: 3 },
    xp: 25,
    hint: 'From equations 1 and 4: D = 7 - B and C = 3B. Substitute into equation 2.',
  },
  {
    id: 116,
    exam: 1,
    number: '1.16',
    difficulty: 'hard',
    chapterId: 3,
    equations: ['1 + 2 × D = C', 'A = 3 × D', '2 × C + 5 = A + B - D', 'B - 6 = D + 4'],
    variables: ['A', 'B', 'C', 'D'],
    answer: { A: 9, B: 13, C: 7, D: 3 },
    xp: 25,
    hint: 'Express A, B, C in terms of D using equations 1, 2, 4. Then substitute into equation 3.',
  },
  {
    id: 117,
    exam: 1,
    number: '1.17',
    difficulty: 'hard',
    chapterId: 3,
    equations: ['C - 4 = B', 'A + 3 × D - 12 = C - B', '2 × B = A', 'D - 2 = B'],
    variables: ['A', 'B', 'C', 'D'],
    answer: { A: 4, B: 2, C: 6, D: 4 },
    xp: 25,
    hint: 'From equations 1 and 4: C = B + 4 and D = B + 2. Equation 3 gives A = 2B.',
  },
  {
    id: 118,
    exam: 1,
    number: '1.18',
    difficulty: 'hard',
    chapterId: 3,
    equations: ['5 × (A + A²) = 550', '3 × (A² + 4A) - B = 400', '30 - B = D × A', 'C + B + A ÷ 2 = 33'],
    variables: ['A', 'B', 'C', 'D'],
    answer: { A: 10, B: 20, C: 8, D: 1 },
    xp: 25,
    hint: 'Equation 1: 5A + 5A² = 550, so A + A² = 110. Try A = 10: 10 + 100 = 110 ✓',
  },
  {
    id: 119,
    exam: 1,
    number: '1.19',
    difficulty: 'hard',
    chapterId: 3,
    equations: ['A = 6 × B - 12', '2 × B = C + 1', 'D = 13 - B', '13 = 3 × B + D - A'],
    variables: ['A', 'B', 'C', 'D'],
    answer: { A: 6, B: 3, C: 5, D: 10 },
    xp: 25,
    hint: 'Express A and D in terms of B, then substitute into equation 4.',
  },
  {
    id: 120,
    exam: 1,
    number: '1.20',
    difficulty: 'hard',
    chapterId: 3,
    equations: ['C + D ÷ 2 - 5 = B + A + 8', '2D + 1 = C', 'D = B + 2', 'A = 10 - D'],
    variables: ['A', 'B', 'C', 'D'],
    answer: { A: 2, B: 6, C: 17, D: 8 },
    xp: 25,
    hint: 'Express A, C in terms of D. Use equation 3 to express B in terms of D. Substitute into equation 1.',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // EXAM 2 - Questions 2.1 to 2.20
  // ═══════════════════════════════════════════════════════════════════════════

  // Easy
  {
    id: 201,
    exam: 2,
    number: '2.1',
    difficulty: 'easy',
    chapterId: 1,
    equations: ['A = B × 3', '8 = B + A'],
    variables: ['A', 'B'],
    answer: { A: 6, B: 2 },
    xp: 10,
    hint: 'Substitute A = 3B into equation 2: 8 = B + 3B = 4B',
  },
  {
    id: 202,
    exam: 2,
    number: '2.2',
    difficulty: 'easy',
    chapterId: 1,
    equations: ['A - B = 5', 'B = A ÷ 2'],
    variables: ['A', 'B'],
    answer: { A: 10, B: 5 },
    xp: 10,
    hint: 'From equation 2: A = 2B. Substitute: 2B - B = 5',
  },
  {
    id: 203,
    exam: 2,
    number: '2.3',
    difficulty: 'easy',
    chapterId: 1,
    equations: ['B + A = 4', 'A = B - 12'],
    variables: ['A', 'B'],
    answer: { A: -4, B: 8 },
    xp: 10,
    hint: 'Substitute A = B - 12 into equation 1: B + (B - 12) = 4',
  },
  {
    id: 204,
    exam: 2,
    number: '2.4',
    difficulty: 'easy',
    chapterId: 1,
    equations: ['B = 2 × A - 7', '14 = 3 × B - A'],
    variables: ['A', 'B'],
    answer: { A: 7, B: 7 },
    xp: 10,
    hint: 'Substitute B = 2A - 7 into equation 2: 14 = 3(2A - 7) - A',
  },
  {
    id: 205,
    exam: 2,
    number: '2.5',
    difficulty: 'easy',
    chapterId: 1,
    equations: ['A⁴ - B = 61', 'B = A + 17'],
    variables: ['A', 'B'],
    answer: { A: 3, B: 20 },
    xp: 10,
    hint: 'Substitute B = A + 17 into equation 1: A⁴ - (A + 17) = 61. Try small values.',
  },
  {
    id: 206,
    exam: 2,
    number: '2.6',
    difficulty: 'easy',
    chapterId: 1,
    equations: ['2 × B = A - 2', 'A = 14 - B'],
    variables: ['A', 'B'],
    answer: { A: 10, B: 4 },
    xp: 10,
    hint: 'Substitute A = 14 - B into equation 1: 2B = (14 - B) - 2',
  },

  // Medium
  {
    id: 207,
    exam: 2,
    number: '2.7',
    difficulty: 'medium',
    chapterId: 2,
    equations: ['A + B = 15', 'A = B - 9', 'C = B ÷ 3'],
    variables: ['A', 'B', 'C'],
    answer: { A: 3, B: 12, C: 4 },
    xp: 15,
    hint: 'From equations 1 and 2: (B - 9) + B = 15, so 2B = 24',
  },
  {
    id: 208,
    exam: 2,
    number: '2.8',
    difficulty: 'medium',
    chapterId: 2,
    equations: ['A = C + 15', 'B = C × 3', 'A ÷ C = 6'],
    variables: ['A', 'B', 'C'],
    answer: { A: 18, B: 9, C: 3 },
    xp: 15,
    hint: 'From equations 1 and 3: A = C + 15 and A = 6C. So 6C = C + 15',
  },
  {
    id: 209,
    exam: 2,
    number: '2.9',
    difficulty: 'medium',
    chapterId: 2,
    equations: ['C - 3 = B', 'B = C ÷ 2', 'C + B = A - 3'],
    variables: ['A', 'B', 'C'],
    answer: { A: 12, B: 3, C: 6 },
    xp: 15,
    hint: 'From equations 1 and 2: C - 3 = C/2, so C/2 = 3, C = 6',
  },
  {
    id: 210,
    exam: 2,
    number: '2.10',
    difficulty: 'medium',
    chapterId: 2,
    equations: ['B - 9 = C', '30 ÷ B = A', 'B = 3 + 2 × C'],
    variables: ['A', 'B', 'C'],
    answer: { A: 2, B: 15, C: 6 },
    xp: 15,
    hint: 'From equations 1 and 3: C = B - 9 and B = 3 + 2C. Substitute: B = 3 + 2(B - 9)',
  },
  {
    id: 211,
    exam: 2,
    number: '2.11',
    difficulty: 'medium',
    chapterId: 2,
    equations: ['B - 3 = A', '4 + A - C = B - 2', '2 × A = B'],
    variables: ['A', 'B', 'C'],
    answer: { A: 3, B: 6, C: 3 },
    xp: 15,
    hint: 'From equations 1 and 3: A = B - 3 and 2A = B. So 2(B - 3) = B',
  },
  {
    id: 212,
    exam: 2,
    number: '2.12',
    difficulty: 'medium',
    chapterId: 2,
    equations: ['C³ + B = 2A + 33', 'A = B + 13', 'B - 2 = A ÷ 6'],
    variables: ['A', 'B', 'C'],
    answer: { A: 18, B: 5, C: 2 },
    xp: 15,
    hint: 'From equations 2 and 3: A = B + 13 and B - 2 = A/6. Substitute: B - 2 = (B + 13)/6',
  },
  {
    id: 213,
    exam: 2,
    number: '2.13',
    difficulty: 'medium',
    chapterId: 2,
    equations: ['2 × A = C + 3', 'C = A + 8', '3 + B ÷ 2 = C - A'],
    variables: ['A', 'B', 'C'],
    answer: { A: 11, B: 10, C: 19 },
    xp: 15,
    hint: 'From equations 1 and 2: 2A = C + 3 and C = A + 8. Substitute: 2A = (A + 8) + 3',
  },

  // Hard
  {
    id: 214,
    exam: 2,
    number: '2.14',
    difficulty: 'hard',
    chapterId: 3,
    equations: ['C = 6 - A', '2 × A = B', 'A ÷ 2 = D', 'A + 3 - D + B = C + 11'],
    variables: ['A', 'B', 'C', 'D'],
    answer: { A: 4, B: 8, C: 2, D: 2 },
    xp: 25,
    hint: 'Express B, C, D in terms of A. Substitute all into equation 4.',
  },
  {
    id: 215,
    exam: 2,
    number: '2.15',
    difficulty: 'hard',
    chapterId: 3,
    equations: ['D ÷ 2 + A - 3 = B + 11', '2 × C ÷ 3 = D', 'D - A = 3', 'D + B = 13'],
    variables: ['A', 'B', 'C', 'D'],
    answer: { A: 3, B: 7, C: 9, D: 6 },
    xp: 25,
    hint: 'From equations 3 and 4: A = D - 3 and B = 13 - D. Substitute into equation 1.',
  },
  {
    id: 216,
    exam: 2,
    number: '2.16',
    difficulty: 'hard',
    chapterId: 3,
    equations: ['D = C ÷ 2', 'B = C - 6', 'A - B ÷ 2 = C + 11 - D', 'A = 2 × C'],
    variables: ['A', 'B', 'C', 'D'],
    answer: { A: 16, B: 2, C: 8, D: 4 },
    xp: 25,
    hint: 'Express A, B, D in terms of C. Substitute into equation 3.',
  },
  {
    id: 217,
    exam: 2,
    number: '2.17',
    difficulty: 'hard',
    chapterId: 3,
    equations: ['2 × A = C + 3', 'A - D + 2 × C = 16', 'D = A + 2', 'B - 5 = A ÷ 2'],
    variables: ['A', 'B', 'C', 'D'],
    answer: { A: 6, B: 8, C: 9, D: 8 },
    xp: 25,
    hint: 'From equations 1 and 3: C = 2A - 3 and D = A + 2. Substitute into equation 2.',
  },
  {
    id: 218,
    exam: 2,
    number: '2.18',
    difficulty: 'hard',
    chapterId: 3,
    equations: ['3 × C = D + 10', 'A = 2 × C + 2', 'A - 2 × C + 5 = B + 2', 'B + 5 = 2 × C'],
    variables: ['A', 'B', 'C', 'D'],
    answer: { A: 12, B: 5, C: 5, D: 5 },
    xp: 25,
    hint: 'From equations 2 and 4: A = 2C + 2 and B = 2C - 5. Substitute into equation 3 to verify.',
  },
  {
    id: 219,
    exam: 2,
    number: '2.19',
    difficulty: 'hard',
    chapterId: 3,
    equations: ['A - C + 2 × B = D + 16', 'A = 2 × C + 12', 'D - 8 = 2 × C', '3 × C + 1 = B'],
    variables: ['A', 'B', 'C', 'D'],
    answer: { A: 16, B: 7, C: 2, D: 12 },
    xp: 25,
    hint: 'Express A, B, D in terms of C. Substitute into equation 1 to find C.',
  },
  {
    id: 220,
    exam: 2,
    number: '2.20',
    difficulty: 'hard',
    chapterId: 3,
    equations: ['C = 2B + 4', 'D - 5 + C ÷ 2 = 2 × B + 1', 'B = 2 × A + 3', 'D = 3B - 6'],
    variables: ['A', 'B', 'C', 'D'],
    answer: { A: 2, B: 7, C: 18, D: 15 },
    xp: 25,
    hint: 'Express C and D in terms of B. Substitute into equation 2 to find B.',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // EXAM 3 - Questions 3.1 to 3.20
  // ═══════════════════════════════════════════════════════════════════════════

  // Easy
  {
    id: 301,
    exam: 3,
    number: '3.1',
    difficulty: 'easy',
    chapterId: 1,
    equations: ['2 = A - B', 'B = 2 × A - 8'],
    variables: ['A', 'B'],
    answer: { A: 6, B: 4 },
    xp: 10,
    hint: 'Substitute B = 2A - 8 into equation 1: 2 = A - (2A - 8)',
  },
  {
    id: 302,
    exam: 3,
    number: '3.2',
    difficulty: 'easy',
    chapterId: 1,
    equations: ['15 + A = B', 'B - 3 = 4 × A'],
    variables: ['A', 'B'],
    answer: { A: 4, B: 19 },
    xp: 10,
    hint: 'From equation 1: B = A + 15. Substitute: (A + 15) - 3 = 4A',
  },
  {
    id: 303,
    exam: 3,
    number: '3.3',
    difficulty: 'easy',
    chapterId: 1,
    equations: ['A ÷ 3 = B + 1', 'A = 15 - B'],
    variables: ['A', 'B'],
    answer: { A: 12, B: 3 },
    xp: 10,
    hint: 'Substitute A = 15 - B into equation 1: (15 - B)/3 = B + 1',
  },
  {
    id: 304,
    exam: 3,
    number: '3.4',
    difficulty: 'easy',
    chapterId: 1,
    equations: ['A - B = 7', 'B = 2 + A ÷ 2'],
    variables: ['A', 'B'],
    answer: { A: 18, B: 11 },
    xp: 10,
    hint: 'From equation 2: B = 2 + A/2. Substitute into equation 1: A - (2 + A/2) = 7',
  },
  {
    id: 305,
    exam: 3,
    number: '3.5',
    difficulty: 'easy',
    chapterId: 1,
    equations: ['B = 17 - A', '2 × A = B - 5'],
    variables: ['A', 'B'],
    answer: { A: 4, B: 13 },
    xp: 10,
    hint: 'Substitute B = 17 - A into equation 2: 2A = (17 - A) - 5',
  },
  {
    id: 306,
    exam: 3,
    number: '3.6',
    difficulty: 'easy',
    chapterId: 1,
    equations: ['A⁰ + 5 = B + 4', 'B = A - 3'],
    variables: ['A', 'B'],
    answer: { A: 5, B: 2 },
    xp: 10,
    hint: 'Remember: A⁰ = 1 for any A ≠ 0. So equation 1 becomes: 1 + 5 = B + 4',
  },

  // Medium
  {
    id: 307,
    exam: 3,
    number: '3.7',
    difficulty: 'medium',
    chapterId: 2,
    equations: ['B - A = 3', '2(B - 1) - 3(B - 4) = 2', 'A² - 5A = 0'],
    variables: ['A', 'B'],
    answer: { A: 5, B: 8 },
    xp: 15,
    hint: 'From equation 3: A(A - 5) = 0, so A = 0 or A = 5. Since A must be positive, A = 5.',
  },
  {
    id: 308,
    exam: 3,
    number: '3.8',
    difficulty: 'medium',
    chapterId: 2,
    equations: ['B - 3 = C - 4', 'C + B = 2 × A - 11', 'C = 7 + B ÷ 2'],
    variables: ['A', 'B', 'C'],
    answer: { A: 10, B: 6, C: 10 },
    xp: 15,
    hint: 'From equation 1: C = B + 1. Substitute into equation 3: B + 1 = 7 + B/2',
  },
  {
    id: 309,
    exam: 3,
    number: '3.9',
    difficulty: 'medium',
    chapterId: 2,
    equations: ['A - 5 = B ÷ 2', 'B = A - 3', 'C - 7 = 2 × B + 2'],
    variables: ['A', 'B', 'C'],
    answer: { A: 7, B: 4, C: 17 },
    xp: 15,
    hint: 'From equations 1 and 2: A - 5 = (A - 3)/2. Solve for A.',
  },
  {
    id: 310,
    exam: 3,
    number: '3.10',
    difficulty: 'medium',
    chapterId: 2,
    equations: ['B - C = 6', 'A - 2 = C', '2 × C - 3 = A + 2'],
    variables: ['A', 'B', 'C'],
    answer: { A: 9, B: 13, C: 7 },
    xp: 15,
    hint: 'From equations 2 and 3: A = C + 2 and 2C - 3 = A + 2. Substitute: 2C - 3 = (C + 2) + 2',
  },
  {
    id: 311,
    exam: 3,
    number: '3.11',
    difficulty: 'medium',
    chapterId: 2,
    equations: ['C - A ÷ 2 + 5 = C + 2', 'B = A ÷ 2', '2 × A - 7 = B + 2'],
    variables: ['A', 'B', 'C'],
    answer: { A: 6, B: 3, C: 5 },
    xp: 15,
    hint: 'From equation 1: -A/2 + 5 = 2, so A/2 = 3, A = 6',
  },
  {
    id: 312,
    exam: 3,
    number: '3.12',
    difficulty: 'medium',
    chapterId: 2,
    equations: ['2 × B - 11 = 13 + C ÷ 2', 'B - A = 5', 'B = C + 9'],
    variables: ['A', 'B', 'C'],
    answer: { A: 8, B: 13, C: 4 },
    xp: 15,
    hint: 'From equation 3: C = B - 9. Substitute into equation 1: 2B - 11 = 13 + (B - 9)/2',
  },
  {
    id: 313,
    exam: 3,
    number: '3.13',
    difficulty: 'medium',
    chapterId: 2,
    equations: ['3 × A + 2 = C ÷ 2', '6 - C ÷ 2 = B - A - 3', 'C - 9 = A'],
    variables: ['A', 'B', 'C'],
    answer: { A: 2, B: 3, C: 11 },
    xp: 15,
    hint: 'From equations 1 and 3: 3A + 2 = C/2 and C = A + 9. Substitute: 3A + 2 = (A + 9)/2',
  },

  // Hard
  {
    id: 314,
    exam: 3,
    number: '3.14',
    difficulty: 'hard',
    chapterId: 3,
    equations: ['D = A - 1', 'A + 5 = 2 × C + 2', 'B = 2A - 6', '7 + D ÷ 2 = 2 × A - B + 5'],
    variables: ['A', 'B', 'C', 'D'],
    answer: { A: 5, B: 4, C: 4, D: 4 },
    xp: 25,
    hint: 'Express B, C, D in terms of A. Substitute into equation 4.',
  },
  {
    id: 315,
    exam: 3,
    number: '3.15',
    difficulty: 'hard',
    chapterId: 3,
    equations: ['2 × A = C', 'B = C ÷ 2 - 4', 'B + C ÷ 2 - A = 2 × D - 1', 'D = C - 15'],
    variables: ['A', 'B', 'C', 'D'],
    answer: { A: 10, B: 1, C: 20, D: 5 },
    xp: 25,
    hint: 'Express everything in terms of A: C = 2A, B = A - 4, D = 2A - 15. Substitute into equation 3.',
  },
  {
    id: 316,
    exam: 3,
    number: '3.16',
    difficulty: 'hard',
    chapterId: 3,
    equations: ['B - 5 + 2 × C = D ÷ 2 + 16', 'D + 3 = A - 5', 'B = 3 + D ÷ 4', 'C = D ÷ 2 + 6'],
    variables: ['A', 'B', 'C', 'D'],
    answer: { A: 16, B: 5, C: 10, D: 8 },
    xp: 25,
    hint: 'Express A, B, C in terms of D. Substitute into equation 1 to find D.',
  },
  {
    id: 317,
    exam: 3,
    number: '3.17',
    difficulty: 'hard',
    chapterId: 3,
    equations: ['A = D + 10', 'A - 13 = C', 'B + 1 = A - 3', 'D - C = 2 × B - A - 6'],
    variables: ['A', 'B', 'C', 'D'],
    answer: { A: 17, B: 13, C: 4, D: 7 },
    xp: 25,
    hint: 'Express A, B, C in terms of D. Substitute into equation 4.',
  },
  {
    id: 318,
    exam: 3,
    number: '3.18',
    difficulty: 'hard',
    chapterId: 3,
    equations: ['A ÷ 2 = B - 1', '2 × C - 7 = A + 3', 'B + D - 3 = A ÷ 2 + 1', 'D + 8 = A - 1'],
    variables: ['A', 'B', 'C', 'D'],
    answer: { A: 14, B: 8, C: 12, D: 5 },
    xp: 25,
    hint: 'From equation 1: A = 2B - 2. From equation 4: D = A - 9. Substitute into equation 3.',
  },
  {
    id: 319,
    exam: 3,
    number: '3.19',
    difficulty: 'hard',
    chapterId: 3,
    equations: ['B = 2 × D - 4', 'D - 5 = C', 'A - D + 2 × B - 5 = C + 13', 'A = D - 6'],
    variables: ['A', 'B', 'C', 'D'],
    answer: { A: 5, B: 18, C: 6, D: 11 },
    xp: 25,
    hint: 'Express A, B, C in terms of D. Substitute into equation 3.',
  },
  {
    id: 320,
    exam: 3,
    number: '3.20',
    difficulty: 'hard',
    chapterId: 3,
    equations: ['A² - A + 56 = 0', 'B - 5 = A ÷ 2', '2 × B - 7 = D', 'C - A - 4 = 2 × B - 6'],
    variables: ['A', 'B', 'C', 'D'],
    answer: { A: 8, B: 9, C: 20, D: 11 },
    xp: 25,
    hint: 'Equation 1 should be A² - A - 56 = 0. Factor: (A - 8)(A + 7) = 0. Since A > 0, A = 8.',
  },
];

export function getMathLevelsByExam(exam) {
  return mathLevels.filter(l => l.exam === exam);
}

export function getMathLevelsByDifficulty(difficulty) {
  return mathLevels.filter(l => l.difficulty === difficulty);
}
